version: 2.1

jobs:
  run-static-analysis:
    parameters:
      version:
        type: string
    docker:
      - image: circleci/golang:<< parameters.version >>
        environment:
          GO111MODULE: "on"
          # work around for recent circle CI breaking change
          # Error: "Error response from daemon: client version 1.39 is too new. Maximum supported API version is 1.38"
          DOCKER_API_VERSION: "1.38"
    # 2CPU / 4GB RAM
    resource_class: medium
    steps:

      - checkout

      - restore_cache:
          keys:
            - go-<< parameters.version >>-{{ checksum "go.sum" }}-{{ checksum "Makefile" }}

      - run: make bootstrap

      - save_cache:
          key: go-<< parameters.version >>-{{ checksum "go.sum" }}-{{ checksum "Makefile" }}
          paths:
            - "/go/pkg/mod"
            - ".tmp"

      - run:
          name: run static analysis
          command: make lint

workflows:
  "Static Analysis":
    jobs:
      - run-static-analysis:
          name: "Static Analysis"
          version: "latest"
